cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove 

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', cart_add, name='cart_add'),
	path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
	path('', cart_detail, name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  


urlpatterns = [
    # path('admin/', include('account.urls', namespace="account")),
    path('admin-panel/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path("create/", include('order.urls', namespace='orders')),
    path('kassa/',include('product.urls', namespace='product')),
    path('account/',include('django.contrib.auth.urls')),
    path('', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import  order_create

app_name = 'order'

urlpatterns = [
    # path("<int:id>/<slug:slug>",order_detail, name="detail"),
    # # path('add/',order_add, name='add'),
    path("",order_create, name="order_create"),
    # path('<int:id>/<slug:slug>', order_remove, name='delete')
]

product/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'product'

urlpatterns = [
    path('',product_list,name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path("<int:id>/<slug:slug>",product_detail, name="detail"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
	quantity = forms.IntegerField(min_value=1, label='Quantity', widget=forms.NumberInput)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST # faqat post usuli orqali kirish uchun
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)

	if form.is_valid():
		cd = form.cleaned_data
		print(cd)
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	print(form)
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	# bu funksia savatni request.sessionda saqlangan ma'lumotlar asosida ko'rsatadi
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'], 'update': True })
	return render(request, 'cart/cart_detail.html', {'cart': cart})

templates/cart/cart_detail.html
{% extends 'kassa.html' %}
{% load static %}

{% block title %}Your shopping cart{% endblock %} 

{% block list %} 
<div class="display1080">
	<h1>Savatcha</h1> 
	<table class="cart"> 
	   <thead class="sarlavha_xona"> 
		   <tr> 
			   <th>Image</th> 
			   <th>Product</th> 
			   <th>Unit price</th> 
			   <th>Price</th> 
			   <th>Quantity</th> 
			   <th>Remove</th> 
		   </tr> 
	   </thead> 
	   <tbody> 
	   {% for item in cart %} 
		   {% with product=item.product %} 
			   <tr> 
				   <td class="rasm_xona"> 
					   <a href="{{ product.get_absolute_url }}"> 
						   <img src="{% if product.image %}{{ product.image.url }} 
						   {% else %}{% static 'images/no_image.png' %}{% endif %}"> 
					   </a> 
				   </td> 
				   <td>{{ product.name }}</td> 
				   <td class="num">{{ item.sotish_narxi }}  Sum</td> 
				   <td class="num">{{ item.total_price }}  Sum</td> 
				   <td>
					   <form action="{% url 'cart:cart_add' product.id %}" method="post">
						   	<span class='minus'>-</span>
							<label for="">
								<input type="hidden" class='current' value="{{ item.quantity }}" name="" id="">
								<span  class='currents'>{{ item.quantity }}</span>
							</label>
							<span class='plus'>+</span>
							<input type="submit" value="Update" class="tasdiq">
							{% csrf_token %}
						   
					   </form>
				   </td> 
				   <td><a href="{% url 'cart:cart_remove' product.id %}" class="uchirish">O'chirish</a></td> 
			   </tr> 
		   {% endwith %} 
	   {% endfor %} 
   
	   <tr class="total"> 
		   <td>Total</td> 
		   <td colspan="4"></td> 
		   <td class="num">{{ cart.get_total_price }} Sum</td> 
	   </tr> 
	   </tbody> 
	</table> 
	<br>
	<p class="text-right"> 
	<a href="{% url 'product:product_list' %}" class="qaytish">Savdoni davom ettirish</a> 
	<a href="{% url 'orders:order_create' %}" class="tasdiq">Checkout</a> 
	</p> 
</div>



<script>
	let current = document.querySelectorAll('.current'),
		currents = document.querySelectorAll('.currents'),
		plus = document.querySelectorAll('.plus'),
		minus = document.querySelectorAll('.minus');
	  
plus.forEach((val,i)=> {
    val.addEventListener("click", ()=>{
        current[i].value = ++current[i].value
		currents[i].textContent = current[i].value
    })
});

minus.forEach((val,i)=> {
    val.addEventListener("click", ()=>{
		if(+current[i].value>0){
			current[i].value = --current[i].value
			currents[i].textContent = current[i].value
		}
	})
});


</script>
{% endblock list %}