account/urls.py
from django.urls import path, include
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.user_login, name='login'),
    path("edit/", views.edit, name="edit"),
    # path("/", include('django.contrib.auth.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path("admin-product-list/",views.ad_pr_list, name="adprlist"),
    path("admin-order-list/",views.ad_or_list, name="adorlist"),
    path("admin-hodim-list/",views.ad_ho_list, name="aduserlist"),
    path("admin-haridor-list/",views.ad_ha_list, name="adhalist"),
    path("<int:pk>/",views.order_detail, name="order_detail"),
    # path('password_change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),




    path('panel/',views.admin_panel, name='admin')
]

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove 

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', cart_add, name='cart_add'),
	path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
	path('', cart_detail, name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  


urlpatterns = [
    # path('admin/', include('account.urls', namespace="account")),
    path('admin-panel/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path("create/", include('order.urls', namespace='orders')),
    path('kassa/',include('product.urls', namespace='product')),
    path('account/',include('django.contrib.auth.urls')),
    path('', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'product'

urlpatterns = [
    path('',product_list,name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path("<int:id>/<slug:slug>",product_detail, name="detail"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <title>
        {% block title %}
        {% endblock title %}       
    </title>
</head>
<body>
    <nav>
        <span class='logo'>A-POS</span>
        {% comment %} {% if request.user.is_authenticated %}
            <ul class="nav-menu">
                <li {% if section == "dashboard" %} class="selected" {% endif %} >
                    <a href="{% url 'account:dashboard' %}">Dashboard</a>
                </li>
                <li {% if section == "kassa" %} class="selected" {% endif %} >
                </li>
            </ul>
            {% endif %} {% endcomment %}

            <span class="user">
                
                {% if request.user.is_authenticated %}
                    <h1>{{request.user.first_name}}</h1>
                    {% if request.user.is_superuser %}
                        <a href="{% url 'account:admin' %}">Admin panel</a>
                    {% endif %}
                <a href="{% url 'product:product_list' %}">Kassa</a>
                <a href="{% url 'logout' %}">Chiqish</a>
            {% else %}
                <a href="{% url 'login' %}">Kirish</a>
                
            {% endif %}
                
        </span>




        {% comment %} <div>
                <h1 class='white'>{{ user.username }}</h1>
            </div>
            <div>
                {% if user.is_superuser %}
                    <a href="{% url 'account:admin' %}">Admin panel</a>  
                {% endif %}
                <a href="{% url 'logout' %}">Chiqish</a>~~~~~
            </div>
        {% else %}
            <div style='height:40px;'> {% endcomment %}
            
        
    </nav>
    {% block content %}
    {% endblock content %}

    
</body>
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/kassa.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Kassa{% endblock title %}

{% block content %}
<section class="asosiy_kassa">
    <div class="bolim1  ">
        {% block list %}
        {% endblock list %}
    </div>
</section>
{% endblock content %}