cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove 

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', cart_add, name='cart_add'),
	path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
	path('', cart_detail, name='cart_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  


urlpatterns = [
    # path('admin/', include('account.urls', namespace="account")),
    path('admin-panel/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path("create/", include('order.urls', namespace='orders')),
    path('kassa/',include('product.urls', namespace='product')),
    path('account/',include('django.contrib.auth.urls')),
    path('', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import  order_create

app_name = 'order'

urlpatterns = [
    # path("<int:id>/<slug:slug>",order_detail, name="detail"),
    # # path('add/',order_add, name='add'),
    path("",order_create, name="order_create"),
    # path('<int:id>/<slug:slug>', order_remove, name='delete')
]

product/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'product'

urlpatterns = [
    path('',product_list,name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path("<int:id>/<slug:slug>",product_detail, name="detail"),
]

order/models.py
from django.db import models
from django.shortcuts import render
from django.contrib.auth.models import User
from product.models import Category , Product 
from django.utils import timezone
from decimal import Decimal
from django.urls import reverse


class TovarlarKirim(models.Model):
    name = models.CharField(max_length=40, verbose_name='Tovar nomi')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Kategoriyasi')
    olingan_narxi = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Olingan narxi')
    sotish_narxi = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Sotilish narxi')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Kim tomonidan olingan')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Olingan kun')
    # writen = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name



class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Ismi')
    last_name = models.CharField(max_length=50, verbose_name='Familiyasi')
    olingan_narx = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Olingan narxi',null=True,blank=True)
    sotilgan_narx = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Sotilgan narxi',null=True,blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    paid = models.BooleanField(default=False, verbose_name="To'langanligi")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana')
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")

    def __str__(self):  
        return f'{self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    def get_absolute_url(self):
        return reverse('account:order_detail', args=[self.pk])



class OrderedItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=12, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

order/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name','last_name','created_by','paid']

order/views.py
from django.shortcuts import render
from .models import OrderedItem
from .forms import OrderCreateForm
from cart.cart import Cart
from product.models import Product

def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			order = form.save(commit=False)
			order.created_by = request.user
			order.save()
			for item in cart:
				price = str(item['price'])
				quantity = str(item['quantity'])
				OrderedItem.objects.create( order=order, product=item['product'], price=price, quantity=quantity) 

				# product = Product.objects.filter(id=item['product'].pk).first()
				# product.quantity = product.quantity - item['quantity']
				# product.save()
			cart.clear()
			contex = {'cart':cart, 'form':form, 'order':order }
			return render(request, 'order/created.html', contex)
		else:
			print(form)
	else:
		form = OrderCreateForm()
	return render(request, 'order/create.html', {'form':form, 'cart':cart})

		

templates/order/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}

{% block content %}
<div class="display1080">
    <form method="post" action='{% url "orders:order_create" %}' style="border:1px solid #ccc">
        {% csrf_token %}
        <div class="container">
            <h1>Order</h1><br>
            <p>Buyurtma ma'lumotlarini to'ldiring</p><br>
            <hr>
            <ul>
                {% for item in cart %}
                    <li>
                        <strong>
                            {{ item.quantity }} x {{ item.product.name }}
                            <span>{{ item.total_price }}  Uzs</span>
                        </strong>
                    </li>
                {% endfor %}
            </ul><br>
            <strong>Umumiy : {{ cart.get_total_price }}  Uzs</strong>
            <br><br>
            <hr>
            {% for item in form %}
            {{item.label}}
            {{item}}
            {% endfor %}
            
            
            
            
            <div class="clearfix">
                <button type="submit" class="signupbtn">Tasdiqlash</button>
            </div>
        </div>
    </form> 
  
    
</div>
{% endblock content %}

templates/order/created.html
{% extends 'base.html' %}

{% block content %}
    <div class='cong-xona'>
        <h1>Tabriklaymiz !!!</h1>
        <p>Xaridingiz muvaffaqiyatli amalga oshirildi buyurtma raqami <strong>{{ order }}</strong></p><br>
        <a class="button" href="{% url 'product:product_list' %}">Savdoni davom ettirish</a>
    </div>
{% endblock content %}

templates/order/detail.html
<a href="{% url 'order:order_create' %}" class="button">Checkout</a>

templates/order/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Savdo tarixi{% endblock title %}

{% block content %}
    <div class='display1080'>
        {% for or in order_item %}
            <div class="order_cont">
                <img src="{{ or.product.image.url }}" alt="">
                <div>
                    <span class="desc">Mahsulot nomi : </span><h1 class="orginal">{{ or.product }}</h1><br>
                    <span class="desc">Buyurtma raqami : </span><h1 class="original">{{ or }}</h1><br>
                    <span class="desc">Mahsulot narxi :  </span><h1 class="original">{{ or.price }} x {{ or.quantity }}</h1><br>
                    <span class="desc">Umumiy narxi :  </span><h1 class="original">{{or.get_cost}}</h1>
                </div>
            </div>
            {% endfor %}
            <strong>Umumiy :  {{ order.get_total_cost }}</strong>
    </div>
{% endblock content %}